### PR TITLE
move rollup parser to devDependencies and upgrade npm module versions

### PR DESCRIPTION
**Pull request by kwindla**

### CODE REVIEW

**Comment by kwindla** [comment]
note: now tested locally. appears to be ready to publish, to me.

**Comment by mattieruth** [comment]
i haven't learned how to singularly test daily-js yet... on the surface it looks fine though.

**Comment by mattieruth** [comment]
with the introduction of #49 are we punting on this PR?

**Comment by kwindla** [comment]
Yes! I'll close this.

**Pull request closed without merging**
