### PR TITLE
Enable various methods for RN

### PR DESCRIPTION
**Pull request by kompfner**
NOTE: review https://github.com/daily-co/daily-js/pull/54 first, as this is dependent on it

### CODE REVIEW

**Comment by mattieruth** [comment]
is there something i should do to test this?

**Comment by kompfner** [comment]
Oh haha I guess not. The test app is living in https://github.com/daily-co/rn-daily-js-playground.

**Comment by mattieruth** [comment]
lgtm? :)

**Comment by mattieruth** [comment]
oh. other than adding instructions for any specific repos you need in daily-js and needing to add the "types:" line to the package.json file

**Comment by kompfner** [comment]
thanks! updated the README: https://github.com/daily-co/rn-daily-js-playground/blob/master/README.md#dailyplayground-machine-specific-setup

**Comment by kompfner** [comment]
hopefully the RN playground setup soon won't require a specific branch of `daily-js`: https://github.com/daily-co/daily-js/pull/54

**Pull request merged**
